version: '3.8'

services:
  cqe-api:
    build: .
    container_name: cqe-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    restart: unless-stopped
    command: python -c "from cqe import CQEClient; c = CQEClient(); print('CQE Ready')"

  redis:
    image: redis:7-alpine
    container_name: cqe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
